// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCbBMMeEPQx37dlL1lykw-kM9w7xV_Dw',
    appId: '1:874636947722:web:ffe4d76216117cbd2f8af3',
    messagingSenderId: '874636947722',
    projectId: 'tictactoe-d10e6',
    authDomain: 'tictactoe-d10e6.firebaseapp.com',
    storageBucket: 'tictactoe-d10e6.firebasestorage.app',
    measurementId: 'G-4LFXN7BGZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCketeuWpgFKa955lDUJXmVinDw9_r_g',
    appId: '1:874636947722:android:4b9cad4dc9a52b232f8af3',
    messagingSenderId: '874636947722',
    projectId: 'tictactoe-d10e6',
    storageBucket: 'tictactoe-d10e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVuX-UgyOt8nWU_FdJcZ5xbVCLxF36-kA',
    appId: '1:874636947722:ios:2dbd03c0199d50c32f8af3',
    messagingSenderId: '874636947722',
    projectId: 'tictactoe-d10e6',
    storageBucket: 'tictactoe-d10e6.firebasestorage.app',
    iosBundleId: 'com.example.fluttercleantictactoegame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVuX-UgyOt8nWU_FdJcZ5xbVCLxF36-kA',
    appId: '1:874636947722:ios:2dbd03c0199d50c32f8af3',
    messagingSenderId: '874636947722',
    projectId: 'tictactoe-d10e6',
    storageBucket: 'tictactoe-d10e6.firebasestorage.app',
    iosBundleId: 'com.example.fluttercleantictactoegame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkCbBMMeEPQx37dlL1lykw-kM9w7xV_Dw',
    appId: '1:874636947722:web:e846d9bcd7b66aa02f8af3',
    messagingSenderId: '874636947722',
    projectId: 'tictactoe-d10e6',
    authDomain: 'tictactoe-d10e6.firebaseapp.com',
    storageBucket: 'tictactoe-d10e6.firebasestorage.app',
    measurementId: 'G-G5S14TZ1P6',
  );
}
