name: tictactoegame
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  shared_preferences: ^2.3.5
  uuid: ^4.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/bear.png
    - assets/background.png
    - assets/random_background_1.png
    - assets/random_background_2.png
    - assets/random_background_3.jpg
    - assets/random_background_4.jpg
    - assets/random_background_5.jpg
    - assets/random_background_6.jpg
    - assets/random_background_7.jpg
    - assets/random_background_8.jpg
  uses-material-design: true


